version: '3'
services:
    app:
        build:
            context: .
        image: ytdl-backend-api:latest
        volumes:
            - .:/home/ytdl/app
        ports:
            - "8000:8000"
        environment:
            LOCAL_ENV: 'true'
            DB_USERNAME: postgres
            DB_HOST: postgres_db
            DB_PASSWORD: dbpass
            DB_NAME: ytdl
        depends_on: 
            - postgres_db

    postgres_db:
        image: postgres:12
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dbpass
            POSTGRES_DB: ytdl

        volumes:
            - postgres-volume:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - 8082:8080

volumes:
    postgres-volume: